#!/bin/sh
DIR="$(dirname "$0")"
FILE_NAME="$DIR/_/husky.sh"

# Conditionally invoke so as to avoid running pnpm commands if this is a clean checkout (ie before installing node modules)
if [ -f $FILE_NAME ]; then
  . $FILE_NAME

  . "$DIR/loadenv"

  npx --no-install commitlint --edit "$1"
fi
